baseURL = "https://cloud.buhlmadsen.dk/"
languageCode = "en-us"
title = "Cloud Notes"
theme = "LoveIt"

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[author]
  name = "Mikkel Buhl Madsen"

[params]
  version = "0.2.X"
  defaultTheme = "auto"
  description = "Notes on Azure, cloud infrastructure and DevOps"

  dateFormat = "2006-01-02"
  showReadingTime = true
  showWordCount = true
  ## Override the Theme settings.
  title = "Cloud Notes"

  [params.author]
    name = "Mikkel Buhl Madsen"
    email = ""
    link = ""

  [params.home]
    [params.home.profile]
      subtitle = "Notes on Azure, Devops and Infrastructure"

[params.page]
  [params.page.toc]
    enable = true
    keepStatic = false
    auto = true

  [params.page.code]
    copy = true
    maxShownLines = 50

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3